=== dheck/Enigma/data/schemas/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' version="0.2" xml:lang="en">
  <xs:annotation>
    <xs:documentation>
      XML schema definitions for Enigma levelpack index
      Copyright Â© 2006 Ronald Lamprecht
      GPL2
    </xs:documentation>
  </xs:annotation>
  <xs:element name="index">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="info" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              Description of the index:
              title    - identifying title of the levelpack
              group    - default levelpack group
              owner    - user name of levelpack creator - "system" for distributed packs
              release  - compatibility version number of levelpack
              revision - modification version number of levelpack
              location - default sorting position of levelpack within a group
              network  - true if levelpack is built for 2-player network game, false for standard single user game
              enigma   - compatibility required Enigma release version.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="title" type="xs:string" use="required"/>
            <xs:attribute name="group" type="xs:string" use="required"/>
            <xs:attribute name="owner" type="xs:string" use="required"/>
            <xs:attribute name="release" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="revision" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="location" type="xs:float" use="required"/>
            <xs:attribute name="network" type="xs:boolean" use="required"/>
            <xs:attribute name="enigma" type="xs:float" use="required"/>
          </xs:complexType>
        </xs:element> <!-- info -->

        <xs:element name="update" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              Url's needed for updates:
              indexurl  - url to obtain updates of the index itself
              levelurl  - url base to download new levels.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="indexurl" type="xs:anyURI" use="required"/>
            <xs:attribute name="levelurl" type="xs:anyURI" use="required"/>
          </xs:complexType>
        </xs:element> <!-- update -->
        
        <xs:element name="attributes" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              A dictionary for future additions. These attributes will be readable
              by future Lua index extensions.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>
                    All simple key-value-properties.
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="key" type="xs:string" use="required"/>
                  <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element> <!-- property -->
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- attributes -->

        <xs:element name="lua" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              Future Lua index extension. Per levelpack control of level menu
              display, levelpack scoring etc..
              Possible elements are: luamain-CDATA, i18n
              Possible attributes are: libpath
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
            </xs:sequence>
            <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
          </xs:complexType>
        </xs:element> <!-- lua -->
        
        <xs:element name="levels" minOccurs="1" maxOccurs="1" >
          <xs:annotation>
            <xs:documentation>
              The sequence of the level elements is the sequence of levels in the pack.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="level" minOccurs="0" maxOccurs="unbounded" >
                <xs:annotation>
                  <xs:documentation>
                    The attributes either identify a level, are cached from the level
                    metadata to avoid unnecessary level loads or describe variation from
                    the level default. See the level description in the reference manual
                    for more information on the single attributes:
                    _seq    - an auto generated counter just for human readability that will never be used
                    _title  - cached level title
                    _xpath  - identifying relative path, url or normed oxyd identifier of the level
                    id      - identifying level id
                    author  - cached level author name
                    score   - cached score version of level
                    rel     - identifying release version of level
                    rev     - identifying revision version of level that announces level updates
                    easy    - cached has easy mode level flag
                    ctrl    - variation in control of level default
                    unit    - variation in score unit of level default
                    target  - variation in score target of level default
                    Attributes with leading underscore are just named this way to generate human
                    readable indices. Future attribute additions are transparent to Enigma 1.0 -
                    they will be ignored but are maintained on all index modifications.
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="_seq" type="xs:positiveInteger" use="optional"/>
                  <xs:attribute name="_title" type="xs:string" use="required"/>
                  <xs:attribute name="_xpath" type="xs:string" use="required"/>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                  <xs:attribute name="author" type="xs:string" use="required"/>
                  <xs:attribute name="score" type="xs:positiveInteger" use="required"/>
                  <xs:attribute name="rel" type="xs:positiveInteger" use="required"/>
                  <xs:attribute name="rev" type="xs:unsignedShort" use="required"/>
                  <xs:attribute name="easy" type="xs:boolean" use="required"/>
                  <xs:attribute name="ctrl" type="controlType" use="required"/>
                  <xs:attribute name="unit" type="scoreunitType" use="required"/>
                  <xs:attribute name="target" type="xs:string" use="required"/>
                  <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
                </xs:complexType>
              </xs:element> <!-- level -->
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- levels -->
        <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element> <!-- index -->

  <xs:simpleType name="controlType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="force"/>
      <xs:enumeration value="balance"/>
      <xs:enumeration value="key"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreunitType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="duration"/>
      <xs:enumeration value="number"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== dheck/Enigma/data/levels/enigma_vi/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">

  <info enigma="1.00" group="Enigma" location="700" network="false" owner="Enigma Team" release="1" revision="1" title="Enigma VI"/>

  <attributes/>

  <levels>
    <level _seq="1" _title="Welcome" _xpath="./welcometopack6_1" author="Raoul Bourquin" ctrl="force" easy="false" id="welcometopack6" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="2" _title="A-way" _xpath="./richi06_1" author="Richi" ctrl="force" easy="false" id="richi06" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="3" _title="Toreador" _xpath="./ral02_1" author="Ronald Lamprecht" ctrl="force" easy="true" id="20060213ral004" rel="1" rev="25" score="1" target="time" unit="duration"/>
    <level _seq="4" _title="Laser Splitting" _xpath="./luc29_1" author="Lukas Schueller" ctrl="force" easy="false" id="luc29" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="5" _title="Oxydrings" _xpath="./raoul13_1" author="Raoul Bourquin" ctrl="force" easy="false" id="raoul13" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="6" _title="Pac Marble" _xpath="./andreas22_1" author="Andreas Lochmann" ctrl="force" easy="false" id="andreas22" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="7" _title="Basketball" _xpath="./ral03_2" author="Ronald Lamprecht" ctrl="force" easy="true" id="20060213ral005" rel="2" rev="25" score="2" target="time" unit="duration"/>
    <level _seq="8" _title="Take the Earth" _xpath="./andreas26_1" author="Andreas Lochmann" ctrl="force" easy="true" id="andreas26" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="9" _title="Evil" _xpath="./spaceman04_1" author="Spaceman" ctrl="force" easy="false" id="spaceman4" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="10" _title="Meditation Disturbance" _xpath="./ral04_1" author="Ronald Lamprecht" ctrl="force" easy="true" id="20060429ral006" rel="1" rev="25" score="1" target="time" unit="duration"/>
    <level _seq="11" _title="Im-pull-se" _xpath="./ralf07_1" author="Ralf Westram" ctrl="force" easy="false" id="ralf07" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="12" _title="Zeus" _xpath="./raoul19_1" author="Raoul Bourquin" ctrl="force" easy="true" id="raoul19" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="13" _title="Rhapsody on Cracks" _xpath="./ral06_1" author="Ronald Lamprecht" ctrl="force" easy="true" id="20060510ral008" rel="1" rev="25" score="1" target="time" unit="duration"/>
    <level _seq="14" _title="Prepare Your Defense" _xpath="./duffy132_1" author="Jacob Scott" ctrl="force" easy="false" id="duffy132" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="15" _title="Cold Way" _xpath="./raoul21_1" author="Raoul Bourquin" ctrl="force" easy="false" id="raoul21" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="16" _title="Laserpowered" _xpath="./raoul20_1" author="Raoul Bourquin" ctrl="force" easy="true" id="raoul20" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="17" _title="Oxydmoron" _xpath="./raoul14_1" author="Raoul Bourquin" ctrl="force" easy="true" id="raoul14" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="18" _title="Bomb raider" _xpath="./alain27_1" author="Alain Busser" ctrl="force" easy="true" id="alain27" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="19" _title="Dancing on Light Beams" _xpath="./andreas28_1" author="Andreas Lochmann" ctrl="force" easy="false" id="andreas28" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="20" _title="- Meditation -" _xpath="./alain25_1" author="Alain Busser + Raoul Bourquin" ctrl="force" easy="false" id="alain25" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="21" _title="ZigZag" _xpath="./ralf06_1" author="Ralf Westram" ctrl="force" easy="true" id="ralf06" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="22" _title="Just Stay Calm" _xpath="./duffy116_1" author="Jacob Scott" ctrl="force" easy="false" id="duffy116" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="23" _title="Checkmate I" _xpath="./andreas29_1" author="Andreas Lochmann" ctrl="force" easy="false" id="andreas29" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="24" _title="The Stable" _xpath="./andreas30_1" author="Andreas Lochmann" ctrl="force" easy="false" id="andreas30" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="25" _title="Chess, Bugs &amp; Rock'n'Roll" _xpath="./andreas31_1" author="Andreas Lochmann" ctrl="force" easy="false" id="andreas31" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="26" _title="Chessing Positions" _xpath="./raoul22_1" author="Raoul Bourquin" ctrl="force" easy="false" id="raoul22" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="27" _title="Just a Maze?" _xpath="./duffy12_1" author="Jacob Scott" ctrl="force" easy="false" id="duffy12" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="28" _title="pool with a pole" _xpath="./alain23_1" author="Alain Busser" ctrl="force" easy="false" id="alain23" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="29" _title="Hot Meditation" _xpath="./ral08_1" author="Ronald Lamprecht" ctrl="force" easy="true" id="20060527ral010" rel="1" rev="26" score="1" target="time" unit="duration"/>
  </levels>

</index>

=== dheck/Enigma/data/levels/enigma_microban/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">

  <info enigma="1.00" group="Sokoban" location="4200" network="false" owner="Enigma Team" release="1" revision="1" title="Microban"/>

  <attributes/>

  <levels>
    <level _seq="1" _title="Microban 58" _xpath="./mic_58" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_58" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="2" _title="Microban 60" _xpath="./mic_60" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_60" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="3" _title="Microban 61" _xpath="./mic_61" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_61" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="4" _title="Microban 62" _xpath="./mic_62" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_62" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="5" _title="Microban 63" _xpath="./mic_63" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_63" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="6" _title="Microban 64" _xpath="./mic_64" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_64" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="7" _title="Microban 65" _xpath="./mic_65" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_65" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="8" _title="Microban 67" _xpath="./mic_67" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_67" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="9" _title="Microban 68" _xpath="./mic_68" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_68" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="10" _title="Microban 69" _xpath="./mic_69" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_69" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="11" _title="Microban 74" _xpath="./mic_74" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_74" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="12" _title="Microban 78" _xpath="./mic_78" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_78" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="13" _title="Microban 79" _xpath="./mic_79" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_79" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="14" _title="Microban 83" _xpath="./mic_83" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_83" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="15" _title="Microban 86" _xpath="./mic_86" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_86" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="16" _title="Microban 93" _xpath="./mic_93" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_93" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="17" _title="Microban 100" _xpath="./mic_100" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_100" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="18" _title="Microban 101" _xpath="./mic_101" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_101" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="19" _title="Microban 102" _xpath="./mic_102" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_102" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="20" _title="Microban 103" _xpath="./mic_103" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_103" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="21" _title="Microban 104" _xpath="./mic_104" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_104" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="22" _title="Microban 105" _xpath="./mic_105" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_105" rel="2" rev="0" score="2" target="time" unit="duration"/>
    <level _seq="23" _title="Microban 106" _xpath="./mic_106" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_106" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="24" _title="Microban 107" _xpath="./mic_107" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_107" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="25" _title="Microban 108" _xpath="./mic_108" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_108" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="26" _title="Microban 110" _xpath="./mic_110" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_110" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="27" _title="Microban 113" _xpath="./mic_113" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_113" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="28" _title="Microban 114" _xpath="./mic_114" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_114" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="29" _title="Microban 115" _xpath="./mic_115" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_115" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="30" _title="Microban 117" _xpath="./mic_117" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_117" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="31" _title="Microban 118" _xpath="./mic_118" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_118" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="32" _title="Microban 121" _xpath="./mic_121" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_121" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="33" _title="Microban 123" _xpath="./mic_123" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_123" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="34" _title="Microban 127" _xpath="./mic_127" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_127" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="35" _title="Microban 132" _xpath="./mic_132" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_132" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="36" _title="Microban 133" _xpath="./mic_133" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_133" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="37" _title="Microban 135" _xpath="./mic_135" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_135" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="38" _title="Microban 136" _xpath="./mic_136" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_136" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="39" _title="Microban 138" _xpath="./mic_138" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_138" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="40" _title="Microban 139" _xpath="./mic_139" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_139" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="41" _title="Microban 141" _xpath="./mic_141" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_141" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="42" _title="Microban 142" _xpath="./mic_142" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_142" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="43" _title="Microban 143" _xpath="./mic_143" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_143" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="44" _title="Microban 144" _xpath="./mic_144" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_144" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="45" _title="Microban 145" _xpath="./mic_145" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_145" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="46" _title="Microban 146" _xpath="./mic_146" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_146" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="47" _title="Microban 150" _xpath="./mic_150" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_150" rel="1" rev="0" score="1" target="time" unit="duration"/>
    <level _seq="48" _title="Microban 151" _xpath="./mic_151" author="David W Skinner" ctrl="force" easy="false" id="microban/mic_151" rel="1" rev="0" score="1" target="time" unit="duration"/>
  </levels>

</index>
