=== dheck/Enigma/data/schemas/level.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' targetNamespace="http://enigma-game.org/schema/level/1" xmlns:el="http://enigma-game.org/schema/level/1" elementFormDefault="qualified" attributeFormDefault="qualified" version="0.2" xml:lang="en">
  <xs:annotation>
    <xs:documentation>
      XML schema definitions for Enigma levels
      Copyright Â© 2006 Ronald Lamprecht
      GPL2
    </xs:documentation>
  </xs:annotation>
  <xs:element name="level">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="protected" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              The protected section is reserved for data from the level author.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="info" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="identity" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="titel" type="xs:string" use="required"/>
                        <xs:attribute name="subtitel" type="xs:string" use="optional"/>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- identity -->
                    <xs:element name="version" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="score" type="xs:unsignedShort" use="required"/>
                        <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                        <xs:attribute name="revision" use="required">
                          <xs:simpleType>
                            <xs:union memberTypes="xs:unsignedShort el:revisionType"/>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="status" type="el:statusType" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- version -->
                    <xs:element name="author" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" default="anonymous" use="optional"/>
                        <xs:attribute name="email" type="xs:anyURI" use="optional"/>
                        <xs:attribute name="homepage" type="xs:anyURI" use="optional"/>
                      </xs:complexType>
                    </xs:element> <!-- author -->
                    <xs:element name="copyright" minOccurs="1" maxOccurs="1" type="xs:string"/>
                    <xs:element name="license" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="type" type="xs:string" use="required"/>
                            <xs:attribute name="open" type="xs:boolean" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element> <!-- license -->
                    <xs:element name="compatibility" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dependency" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="path" type="xs:string" use="required"/>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                              <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                              <xs:attribute name="preload" type="xs:boolean" use="required"/>
                              <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                            </xs:complexType>
                          </xs:element> <!-- dependency -->
                          <xs:element name="externaldata" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="path" type="xs:string" use="optional"/>
                              <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                            </xs:complexType>
                          </xs:element> <!-- externaldata -->
                          <xs:element name="editor" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required"/>
                              <xs:attribute name="version" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element> <!-- editor -->
                          <xs:element name="extensions" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element> <!-- extensions -->
                        </xs:sequence>
                        <xs:attribute name="enigma" type="xs:float" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- compatibility -->
                    <xs:element name="modes" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="easy" type="xs:boolean" use="required"/>
                        <xs:attribute name="single" type="xs:boolean" use="required"/>
                        <xs:attribute name="network" type="xs:boolean" use="required"/>
                        <xs:attribute name="control" type="el:controlType" use="optional" default="force"/>
                        <xs:attribute name="scoreunit" type="el:scoreunitType" use="optional" default="duration"/>
                        <xs:attribute name="scoretarget" type="xs:string" use="optional" default="time"/>
                      </xs:complexType>
                    </xs:element> <!-- modes -->
                    <xs:element name="comments" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="credits" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:token">
                                  <xs:attribute name="showinfo" type="xs:boolean" use="optional" default="false"/>
                                  <xs:attribute name="showstart" type="xs:boolean" use="optional" default="false"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- credits -->
                          <xs:element name="dedication" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:token">
                                  <xs:attribute name="showinfo" type="xs:boolean" use="optional" default="false"/>
                                  <xs:attribute name="showstart" type="xs:boolean" use="optional" default="false"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- dedication -->
                          <xs:element name="code" minOccurs="0" maxOccurs="1" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element> <!-- comments -->
                    <xs:element name="update" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- update -->
                    <xs:element name="upgrade" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                        <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- upgrade -->
                    <xs:element name="preview" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
                      </xs:complexType>
                    </xs:element> <!-- preview -->
                    <xs:element name="score" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="easy" type="el:scoreType" use="required"/>
                        <xs:attribute name="difficult" type="el:scoreType" use="required"/> 
                      </xs:complexType>
                    </xs:element> <!-- score -->
                    
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>

                  </xs:sequence>
                  <xs:attribute name="type" type="el:fileType" use="required"/>
                </xs:complexType>
              </xs:element> <!-- info -->
              
              <xs:element name="elements" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- elements -->
              
              <xs:element name="luamain" minOccurs="0" maxOccurs="1" type="xs:string"/>
              
              <xs:any namespace="##other" minOccurs="0" maxOccurs="1" processContents="skip">
                <xs:annotation>
                  <xs:documentation>
                    Any external level editor is free to include an element of its own
                    namespace for storage of any extensions. This element is ignored by
                    enigma. The editor is free to supply an additional schema for its 
                    element definitions.
                  </xs:documentation>
                </xs:annotation>
              </xs:any>
              
              <xs:element name="i18n" minOccurs="1" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="string" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="english" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="translate" type="xs:boolean" default="true"/>
                                  <xs:attribute name="comment" type="xs:string" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- english -->
                          <xs:element name="translation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="lang" type="xs:language" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- translation -->
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- string -->
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- i18n -->
              
              <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>

            </xs:sequence>
            <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
          </xs:complexType>
        </xs:element> <!-- protected -->
        
        <xs:element name="public" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              The pubic section for not validated additions by others. All info
              in public is handeled with care by enigma. Translations will be
              suggested to the official translators and only be used if confirmed
              or missing in the translators translations.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="i18n" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="string" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="translation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="lang" type="xs:language" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- translation -->
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:ID" use="required">
                          <xs:annotation>
                            <xs:documentation>
                              Usage of type xs:ID instead of xs:string is required by evaluation
                              XSLT stylesheets. 
                              It limits the public/i18n/strings to key-identifier usage instead
                              of original complete english string as key usage. But this is not
                              too bad, because it reduces errors due to changed english strings 
                              in the protected area.
                              The ID type guarantees us uniqueness within public/i18n and allows
                              stylesheets and programs to use XPaths to crossover from a 
                              protected/i18n/string to the corresponding public/i18n/string.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element> <!-- string -->
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- i18n -->
              <xs:element name="upgrade" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="url" type="xs:anyURI" use="required"/>
                  <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                </xs:complexType>
              </xs:element> <!-- upgrade -->
              <xs:element name="extensions" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- extensions -->
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- public -->
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="stringkey">
      <xs:selector xpath="el:protected/el:i18n/el:string"/>
      <xs:field xpath="@el:key"/>
    </xs:key>
    <xs:keyref name="translationkey" refer="el:stringkey">
      <xs:selector xpath="el:public/el:i18n/el:string"/>
      <xs:field xpath="@el:key"/>
    </xs:keyref>
  </xs:element>
  
  <xs:simpleType name="fileType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="level"/>
      <xs:enumeration value="multilevel"/>
      <xs:enumeration value="library"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="revisionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="$Revision[ ]*[\d]*[ ]*$"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="statusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="released"/>
      <xs:enumeration value="stable"/>
      <xs:enumeration value="test"/>
      <xs:enumeration value="experimental"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="controlType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="force"/>
      <xs:enumeration value="balance"/>
      <xs:enumeration value="key"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreunitType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="duration"/>
      <xs:enumeration value="number"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreType">
    <xs:restriction base="xs:string">
      <xs:pattern value="-|([ \d]?\d:[012345]\d)|(\d)+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== dheck/Enigma/data/levels/enigma_vi/ral04_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected >
    <el:info el:type="level">
      <el:identity el:title="Meditation Disturbance" el:subtitle="Hit by a bolting horse" el:id="20060429ral006"/>
      <el:version el:score="1" el:release="1" el:revision="$Revision: 15 $" el:status="stable"/>
      <el:author  el:name="Ronald Lamprecht" el:email="ral@users.berlios.de"/>
      <el:copyright>Copyright © 2006 Ronald Lamprecht</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="0.92"/>
      <el:modes el:easy="true" el:single="true" el:network="false"/>
      <el:score el:easy="0:11" el:difficult="0:42"/>
    </el:info>
    <el:luamain><![CDATA[
enigma.ConserveLevel = FALSE

levelw = 20
levelh = 13

create_world( levelw, levelh)
draw_border("st-glass")
fill_floor("fl-bluegray", 0,0,levelw,levelh)
set_item("it-hollow", 3, 3)
set_item("it-hollow", 3, 9)
set_item("it-hollow", 16, 3)
set_item("it-hollow", 16, 9)

set_actor("ac-whiteball-small", 7.5, 5.5, {player=0})
set_actor("ac-whiteball-small", 12.5, 5.5, {player=0})
set_actor("ac-whiteball-small", 7.5, 7.5, {player=0})
set_actor("ac-whiteball-small", 12.5, 7.5, {player=0})


if difficult then
    horseforce = 7.2
else
    horseforce = 6
end

set_actor("ac-horse",16.5, 6.5, {force=horseforce, target1="16 3", target2="3 3", target3="3 9", target4="16 9" })
    ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="true"/>
        <el:translation el:lang="de">Ruhestörung bei der Meditation</el:translation>
      </el:string>
      <el:string el:key="subtitle">
        <el:english el:translate="true" el:comment="free translatable joke about being hit by a horse"/>
        <el:translation el:lang="de">Ich glaub mich tritt ein Pferd</el:translation>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>

=== dheck/Enigma/data/levels/enigma_esprit/esprit80_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="- Meditation -" el:subtitle="esprit 80" el:id="ss_esp80"/>
      <el:version el:score="1" el:release="1" el:revision="0" el:status="released"/>
      <el:author  el:name="Sven Siggelkow" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2003 Sven Siggelkow</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="0.92">
      </el:compatibility>
      <el:modes el:easy="false" el:single="true" el:network="false"/>
      <el:comments>
        <el:code>Lua 5.1 and XML converted by Leveladministrators</el:code>
      </el:comments>
      <el:score el:easy="-" el:difficult="-"/>
    </el:info>
    <el:luamain><![CDATA[
levelw = 20
levelh = 13
create_world(levelw, levelh)

fill_floor("fl-bluegray")

enigma.AddConstantForce(0,20)

function renderLine( line, pattern)
    for i=1, strlen(pattern) do
      local c = strsub( pattern, i, i)
      if c ==   "#" then
         set_stone("st-rock6",i-1,line)
      elseif c=="H" then
         hollow(i-1,line)
        end
    end
end
--              01234567890123456789
renderLine(00, "####################")
renderLine(01, "#                  #")
renderLine(02, "#                  #")
renderLine(03, "#                  #")
renderLine(04, "#        #H#       #")  
renderLine(05, "#        #H#       #")
renderLine(06, "#        #H#       #")
renderLine(07, "#        #H#       #")
renderLine(08, "#                  #")
renderLine(09, "#                  #")
renderLine(10, "#                  #")
renderLine(11, "#                  #")
renderLine(12, "####################")
--              01234567890123456789

set_actor("ac-whiteball-small", 2.5, 11.5, {player=0})
set_actor("ac-whiteball-small",7.5, 11.5, {player=0})
set_actor("ac-whiteball-small", 13.5, 11.5, {player=0})
set_actor("ac-whiteball-small",17.5, 11.5, {player=0})
    ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>

=== dheck/Enigma/data/levels/enigma_iv/duffy104_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Termites" el:subtitle="" el:id="duffy104"/>
      <el:version el:score="1" el:release="1" el:revision="0" el:status="released"/>
      <el:author  el:name="Jacob Scott" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2004 Jacob Scott</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="0.92">
      </el:compatibility>
      <el:modes el:easy="false" el:single="true" el:network="false"/>
      <el:comments>
        <el:code>Lua 5.1 and XML converted by Leveladministrators</el:code>
      </el:comments>
      <el:score el:easy="-" el:difficult="-"/>
    </el:info>
    <el:luamain><![CDATA[
rooms_wide=1
rooms_high=1

levelw=1+(19*rooms_wide)
levelh=1+(12*rooms_high)

create_world( levelw, levelh)
enigma.SetCompatibility("oxyd1")
enigma.ConserveLevel=FALSE

fill_floor("fl-hay", 0,0,levelw,levelh)

function renderLine( line, pattern)
	for i=1, strlen(pattern) do
		local c = strsub( pattern, i, i)
		if c =="#" then
			set_stone( "st-glass1", i-1, line)
		elseif c =="S" then
		   set_stone( "st-spitter", i-1, line)
		elseif c =="T" then
			set_stone( "st-thief", i-1, line)
		elseif c =="B" then
			set_stone( "st-glass1", i-1, line)
		   set_item("it-blackbomb",i-1,line)
		elseif c =="W" then
			set_stone( "st-glass1", i-1, line)
		   set_item("it-whitebomb",i-1,line)
		elseif c == "o" then
			oxyd( i-1, line)
		elseif c == "*" then
			set_stone( "st-brownie", i-1, line)
                elseif c == "!" then
			abyss(i-1,line)
		elseif c == "~" then
		   set_floor("fl-water",i-1,line)
		elseif c=="z" then
		   set_actor("ac-blackball", i-1,line+.5, {player=0})
		elseif c=="y" then
		   set_actor("ac-whiteball", i-1,line+.5, {player=1})
		elseif c == "g" then
			draw_stones("st-grate1",{i-1,line}, {1,1}, 1)
		elseif c=="+" then
			set_stone( "st-wood", i-1, line)
		elseif c=="=" then
			set_floor("fl-space",i-1,line)
		elseif c=="b" then
		   set_item("it-blackbomb",i-1,line)
		elseif c=="w" then
		   set_item("it-whitebomb",i-1,line)
		elseif c=="O" then
		   set_item("it-extralife",i-1,line)
		elseif c=="1" then
		   set_item("it-blackbomb",i-1,line,{name="b1"})
		elseif c=="f" then
		   set_item("it-floppy",i-1,line)
		elseif c=="A" then
		   set_stone("st-floppy",i-1,line,{action="openclose",target="door1"})
		elseif c=="a" then
			doorh( i-1,line, {name="door1"})
		elseif c=="%" then
		   set_stone("st-floppy",i-1,line,{action="openclose",target="door2"})
		elseif c=="$" then
			doorh( i-1,line, {name="door2"})
		elseif c=="C" then
		   set_stone("st-floppy",i-1,line,{action="openclose",target="door3"})
		elseif c=="c" then
			doorh( i-1,line, {name="door3"})
		elseif c=="D" then
		   set_stone("st-floppy",i-1,line,{action="openclose",target="door4"})
		elseif c=="d" then
		   doorh( i-1,line, {name="door4"})
		elseif c=="L" then
 			set_stone("st-oneway_black", i-1,line, {orientation=enigma.WEST})
	     end
	end	
end

renderLine(00,"####################")
renderLine(01,"#o#       z      #o#")
renderLine(02,"#aA bbbbbbbbbbbb %$#")
renderLine(03,"# 1bb          bbb #")
renderLine(04,"# #   bbbbbbbb   b #")
renderLine(05,"# bbbbb #####bbb b #")
renderLine(06,"# b   + Bb f# +b b #")
renderLine(07,"# b bbbbB+###bbb b #")
renderLine(08,"# b   + bbbbbb+  b #")
renderLine(09,"# bbb     +    bbb #")
renderLine(10,"#dD bbbbbbbbbbbb Cc#")
renderLine(11,"#o#              #o#")
renderLine(12,"####################")

oxyd_shuffle()

b1=enigma.GetNamedObject("b1")

enigma.SendMessage(b1,"ignite",nil)
    ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>

=== dheck/Enigma/data/levels/oxydextra/oxe18_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Shogun Master" el:subtitle="" el:id="martin28"/>
      <el:version el:score="1" el:release="1" el:revision="0" el:status="released"/>
      <el:author  el:name="Martin Hawlisch" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2003 Martin Hawlisch</el:copyright>
      <el:license el:type="GPL version 2" el:open="true"/>
      <el:compatibility el:enigma="0.92">
      </el:compatibility>
      <el:modes el:easy="false" el:single="true" el:network="false"/>
      <el:comments>
        <el:code>Lua 5.1 and XML converted by Leveladministrators</el:code>
      </el:comments>
      <el:score el:easy="-" el:difficult="-"/>
    </el:info>
    <el:luamain><![CDATA[
levelw = 20
levelh = 13

create_world( levelw, levelh)
fill_floor( "fl-plank", 0, 0, levelw, levelh)

function renderLine( line, pattern)
    for i=1, strlen(pattern) do
        local c = strsub( pattern, i, i)
        if c == "o" then
            oxyd( i-1, line)
    elseif c == "#" then
        set_stone( "st-brick", i-1, line)
        end
    end
end

renderLine(  0, "############o#######")
renderLine(  1, "#   #  ##  # ##  # #")
renderLine(  2, "#                  #")
renderLine(  3, "## ## ###  # ##  # #")
renderLine(  4, "#  #      #      #o#")
renderLine(  5, "## # ####  # ### ###")
renderLine(  6, "##    o#           #")
renderLine(  7, "#  ###o# # # ### ###")
renderLine(  8, "##   # #         #o#")
renderLine(  9, "##   # # # # ### # #")
renderLine( 10, "#    # #           #")
renderLine( 11, "## #         # # # #")
renderLine( 12, "##o###########o#o###")

oxyd_shuffle()

shogundot1( 6, 4, {action="openclose", target="door1"})
shogundot1( 7, 4, {action="openclose", target="door2"})
shogundot1( 8, 4, {action="openclose", target="door3"})
shogundot1( 9, 4, {action="openclose", target="door4"})
shogundot1(10, 3, {action="openclose", target="door6"})
shogundot1(10, 5, {action="openclose", target="door7"})
shogundot1( 8, 6, {action="openclose", target="door8"})
shogundot1(11, 6, {action="openclose", target="door5"})

set_stone( "st-shogun-s", 3, 6)
set_stone( "st-shogun-s",11, 2)
set_stone( "st-shogun-s",13, 6)

doorh( 2,11, {name="door1"})
doorv( 5, 6, {name="door2"})
doorh( 6, 8, {name="door3"})
doorh(14,11, {name="door4"})
doorh(18, 3, {name="door5"})
doorh(12, 1, {name="door6"})
doorh(18, 9, {name="door7"})
doorh(16,11, {name="door8"})

set_actor("ac-blackball", 9.5, 5.5)
    ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>
