=== dheck/Enigma/data/schemas/level.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' targetNamespace="http://enigma-game.org/schema/level/1" xmlns:el="http://enigma-game.org/schema/level/1" elementFormDefault="qualified" attributeFormDefault="qualified" version="0.2" xml:lang="en">
  <xs:annotation>
    <xs:documentation>
      XML schema definitions for Enigma levels
      Copyright Â© 2006 Ronald Lamprecht
      GPL2
    </xs:documentation>
  </xs:annotation>
  <xs:element name="level">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="protected" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              The protected section is reserved for data from the level author.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="info" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="identity" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="titel" type="xs:string" use="required"/>
                        <xs:attribute name="subtitel" type="xs:string" use="optional"/>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- identity -->
                    <xs:element name="version" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="score" type="xs:unsignedShort" use="required"/>
                        <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                        <xs:attribute name="revision" use="required">
                          <xs:simpleType>
                            <xs:union memberTypes="xs:unsignedShort el:revisionType"/>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="status" type="el:statusType" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- version -->
                    <xs:element name="author" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" default="anonymous" use="optional"/>
                        <xs:attribute name="email" type="xs:anyURI" use="optional"/>
                        <xs:attribute name="homepage" type="xs:anyURI" use="optional"/>
                      </xs:complexType>
                    </xs:element> <!-- author -->
                    <xs:element name="copyright" minOccurs="1" maxOccurs="1" type="xs:string"/>
                    <xs:element name="license" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="type" type="xs:string" use="required"/>
                            <xs:attribute name="open" type="xs:boolean" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element> <!-- license -->
                    <xs:element name="compatibility" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dependency" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="path" type="xs:string" use="required"/>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                              <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                              <xs:attribute name="preload" type="xs:boolean" use="required"/>
                              <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                            </xs:complexType>
                          </xs:element> <!-- dependency -->
                          <xs:element name="externaldata" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="path" type="xs:string" use="optional"/>
                              <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                            </xs:complexType>
                          </xs:element> <!-- externaldata -->
                          <xs:element name="editor" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required"/>
                              <xs:attribute name="version" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element> <!-- editor -->
                          <xs:element name="extensions" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element> <!-- extensions -->
                        </xs:sequence>
                        <xs:attribute name="enigma" type="xs:float" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- compatibility -->
                    <xs:element name="modes" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="easy" type="xs:boolean" use="required"/>
                        <xs:attribute name="single" type="xs:boolean" use="required"/>
                        <xs:attribute name="network" type="xs:boolean" use="required"/>
                        <xs:attribute name="control" type="el:controlType" use="optional" default="force"/>
                        <xs:attribute name="scoreunit" type="el:scoreunitType" use="optional" default="duration"/>
                        <xs:attribute name="scoretarget" type="xs:string" use="optional" default="time"/>
                      </xs:complexType>
                    </xs:element> <!-- modes -->
                    <xs:element name="comments" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="credits" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:token">
                                  <xs:attribute name="showinfo" type="xs:boolean" use="optional" default="false"/>
                                  <xs:attribute name="showstart" type="xs:boolean" use="optional" default="false"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- credits -->
                          <xs:element name="dedication" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:token">
                                  <xs:attribute name="showinfo" type="xs:boolean" use="optional" default="false"/>
                                  <xs:attribute name="showstart" type="xs:boolean" use="optional" default="false"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- dedication -->
                          <xs:element name="code" minOccurs="0" maxOccurs="1" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element> <!-- comments -->
                    <xs:element name="update" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- update -->
                    <xs:element name="upgrade" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                        <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- upgrade -->
                    <xs:element name="preview" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
                      </xs:complexType>
                    </xs:element> <!-- preview -->
                    <xs:element name="score" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="easy" type="el:scoreType" use="required"/>
                        <xs:attribute name="difficult" type="el:scoreType" use="required"/> 
                      </xs:complexType>
                    </xs:element> <!-- score -->
                    
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>

                  </xs:sequence>
                  <xs:attribute name="type" type="el:fileType" use="required"/>
                </xs:complexType>
              </xs:element> <!-- info -->
              
              <xs:element name="elements" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- elements -->
              
              <xs:element name="luamain" minOccurs="0" maxOccurs="1" type="xs:string"/>
              
              <xs:any namespace="##other" minOccurs="0" maxOccurs="1" processContents="skip">
                <xs:annotation>
                  <xs:documentation>
                    Any external level editor is free to include an element of its own
                    namespace for storage of any extensions. This element is ignored by
                    enigma. The editor is free to supply an additional schema for its 
                    element definitions.
                  </xs:documentation>
                </xs:annotation>
              </xs:any>
              
              <xs:element name="i18n" minOccurs="1" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="string" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="english" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="translate" type="xs:boolean" default="true"/>
                                  <xs:attribute name="comment" type="xs:string" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- english -->
                          <xs:element name="translation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="lang" type="xs:language" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- translation -->
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- string -->
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- i18n -->
              
              <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>

            </xs:sequence>
            <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
          </xs:complexType>
        </xs:element> <!-- protected -->
        
        <xs:element name="public" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              The pubic section for not validated additions by others. All info
              in public is handeled with care by enigma. Translations will be
              suggested to the official translators and only be used if confirmed
              or missing in the translators translations.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="i18n" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="string" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="translation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="lang" type="xs:language" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- translation -->
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:ID" use="required">
                          <xs:annotation>
                            <xs:documentation>
                              Usage of type xs:ID instead of xs:string is required by evaluation
                              XSLT stylesheets. 
                              It limits the public/i18n/strings to key-identifier usage instead
                              of original complete english string as key usage. But this is not
                              too bad, because it reduces errors due to changed english strings 
                              in the protected area.
                              The ID type guarantees us uniqueness within public/i18n and allows
                              stylesheets and programs to use XPaths to crossover from a 
                              protected/i18n/string to the corresponding public/i18n/string.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element> <!-- string -->
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- i18n -->
              <xs:element name="upgrade" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="url" type="xs:anyURI" use="required"/>
                  <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                </xs:complexType>
              </xs:element> <!-- upgrade -->
              <xs:element name="extensions" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- extensions -->
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- public -->
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="stringkey">
      <xs:selector xpath="el:protected/el:i18n/el:string"/>
      <xs:field xpath="@el:key"/>
    </xs:key>
    <xs:keyref name="translationkey" refer="el:stringkey">
      <xs:selector xpath="el:public/el:i18n/el:string"/>
      <xs:field xpath="@el:key"/>
    </xs:keyref>
  </xs:element>
  
  <xs:simpleType name="fileType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="level"/>
      <xs:enumeration value="multilevel"/>
      <xs:enumeration value="library"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="revisionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="$Revision[ ]*[\d]*[ ]*$"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="statusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="released"/>
      <xs:enumeration value="stable"/>
      <xs:enumeration value="test"/>
      <xs:enumeration value="experimental"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="controlType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="force"/>
      <xs:enumeration value="balance"/>
      <xs:enumeration value="key"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreunitType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="duration"/>
      <xs:enumeration value="number"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreType">
    <xs:restriction base="xs:string">
      <xs:pattern value="-|([ \d]?\d:[012345]\d)|(\d)+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== dheck/Enigma/data/levels/enigma_ix/devnull38_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Crabwise III" el:subtitle="" el:id="devnull38"/>
      <el:version el:score="1" el:release="1" el:revision="1" el:status="released"/>
      <el:author  el:name="/dev/null" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2009 dev0</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="1.10">
        <el:dependency el:path="lib/libpuzzle" el:id="lib/libpuzzle" el:release="3" el:preload="true"/>
      </el:compatibility>
      <el:modes el:easy="true" el:single="true" el:network="false"/>
      <el:score el:easy="3:45" el:difficult="3:45"/>
    </el:info>
    <el:luamain><![CDATA[
wo["AllowSuicide"] = false
wo["ProvideExtralifes"] = not wo["IsDifficult"]

ti[" "] = {"fl_rock"}
ti["~"] = {"fl_water"}
ti["."] = {"fl_abyss"}
ti["#"] = ti({"fl_bridge"}) .. {"st_redrock"}
ti["X"] = ti[" "] .. {"st_grate_cross"}
ti["x"] = cond(wo["IsDifficult"], ti["~"] .. {"st_grate_cross"}, ti["~"])
ti["+"] = cond(wo["IsDifficult"], ti[" "], ti["X"])
ti["w"] = {"st_puzzle_blue", "pa", connections = "w", intensity = 0}
ti["s"] = {"st_puzzle_blue", "pb", connections = "se", intensity = 0}
ti["n"] = {"st_puzzle_blue", "pc", connections = "nw", intensity = 0}
ti["e"] = {"st_puzzle_blue", "pd", connections = "e", intensity = 0}
ti["W"] = {"st_puzzle_blue", "pA", connections = "w", intensity = 0}
ti["-"] = {"st_puzzle_blue", "pB", connections = "ew", intensity = 0}
ti["E"] = {"st_puzzle_blue", "pC", connections = "e", intensity = 0}
ti["a"] = ti({"fl_hay_framed"}) .. {"it_trigger", target = "toggleDoors", action = "signal", invisible = true}
ti["A"] = {"st_door_a", "doors#"}
ti["b"] = ti({"fl_hay_framed"}) .. {"it_trigger", target = "toggleBridges", action = "signal", invisible = true}
ti["B"] = {"fl_bridge", "bridges#"}
ti["1"] = {"st_pull", "nav01"}
ti["2"] = {"st_swap"}
ti["3"] = {"st_box_rock"}
ti["4"] = {"st_pull", "nav02"}
ti["O"] = {"st_oxyd_a", oxydcolor = OXYD_RED, static = true}
ti["@"] = {"#ac_marble_black"}

wo(ti, " ", {
    "##################O#",
    "#     ~~x~X        #",
    "#  ne ~x~~X        #",
    "#     ~~~~X@ 2a1a3 #",
    "# ws  ~~x~X        #",
    "#     ~x~~X        #",
    "##A#A###############",
    "#       .....X     #",
    "#       ..BBBX  E  #",
    "#   4   ..B..+ b-b #",
    "#       BBB..X  W  #",
    "#       .....X     #",
    "##################O#"})

if wo["IsDifficult"] then
    wo:add({"ot_wire", anchor1 = "nav01", anchor2 = "pa"})
    wo:add({"ot_wire", anchor1 = "nav01", anchor2 = "pd"})
    wo:add({"ot_wire", anchor1 = "nav02", anchor2 = "pA"})
    wo:add({"ot_wire", anchor1 = "nav02", anchor2 = "pC"})
else
    wo:add({"ot_wire", anchor1 = "nav01", anchor2 = "pa"})
    wo:add({"ot_wire", anchor1 = "nav02", anchor2 = "pC"})
end
wo:add({"ot_counter", "toggleDoors", state = 0, target = "doors#*", action_2 = "open", action_1 = "close"})
wo:add({"ot_counter", "toggleBridges", state = 0, target = "bridges#*", action_2 = "close", action_1 = "open"})
 ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="true"/>
        <el:translation el:lang="de">Hintenrum III</el:translation>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>

=== dheck/Enigma/data/levels/enigma_ii/alain16_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Enigmastermind" el:subtitle="" el:id="alain16"/>
      <el:version el:score="1" el:release="2" el:revision="5" el:status="released"/>
      <el:author el:name="Alain Busser" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2006 Alain Busser</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="1.10">
        <el:dependency el:path="lib/libmath" el:id="lib/libmath" el:release="1" el:preload="true"/>
      </el:compatibility>
      <el:modes el:easy="false" el:single="true" el:network="false"/>
      <el:comments><el:code>Game code by R. Bourquin</el:code></el:comments>
      <el:score el:easy="-" el:difficult="2:14"/>
    </el:info>
    <el:luamain><![CDATA[
wo["ConserveLevel"] = false

ti[" "] = {"fl_dark"}
ti["#"] = {"st_rawglass"}
ti["t"] = {"it_document", text="text1"}
ti["u"] = {"it_document", text="text2"}
ti["a"] = {"fl_water", name="c_%1", _id=1}
ti["b"] = {"fl_lawn", name="c_%2", _id=2}
ti["c"] = {"fl_red", name="c_%3", _id=3}
ti["d"] = {"fl_sahara", name="c_%4", _id=4}
ti["e"] = {"fl_sand", name="c_%5", _id=5}
ti["f"] = {"fl_redslab", name="c_%6", _id=6}
ti["colchooser"] = {"st_switch", name="chooser_c_%%", target="color_chooser", _col="c_%%", _col_choosen=false}
ti["poschooser"] = {"st_switch", name="chooser_p_%%", target="set_color", _col=""}
ti["X"] = {"st_switch", name="evaluator", target="evaluate", _rounds=5, _active=true}
ti["="] = {"st_door", name="thedoor", flavor="d", faces="ew"}
ti["O"] = {"st_oxyd"}
ti["@"] = {"#ac_marble", name="ball", _col="c_%1", _col_used=false}

wo(res.autotile(ti, {"A", "F", "colchooser"}, {"1", "4", "poschooser"})," ",{
    "#O#O#O#O#O#O########",
    "#           =    Aa#",
    "#############    Bb#",
    "# # # # # # 1    Cc#",
    "# # # # # # 2 t  Dd#",
    "# # # # # # 3    Ee#",
    "# # # # # # 4    Ff#",
    "#############  @ ###",
    "# # # # # # #    # #",
    "# # # # # # #    # #",
    "# # # # # # #    # #",
    "# # # # # # #u   # #",
    "#############X######"})

wo:shuffleOxyd()

local colors = {"fl_water", "fl_lawn", "fl_red", "fl_sahara", "fl_sand", "fl_redslab"}

function color_chooser(value, sender)
    if not sender["_col_choosen"] then
        wo[no["marker"]] = {"st_nil"}
        wo[sender + E] = {"st_lightglass", name="marker"}
        no["ball"]["_col"] = sender["_col"]    -- store the color choosen
        no["ball"]["_col_used"] = false        -- and assure its not used yet
    end
end

function set_color(value, sender)
    if no["evaluator"]["_active"] and not no["ball"]["_col_used"] then
        no["chooser_"..sender["_col"]]["_col_choosen"] = false       -- reallow the overwritten color if any
        no["chooser_"..no["ball"]["_col"]]["_col_choosen"] = true    -- mark the choosen color as used
        sender["_col"] = no["ball"]["_col"]                          -- store the current color at senders position
        wo[sender + 2*no["evaluator"]["_rounds"]*W + W] = {colors[no[no["ball"]["_col"]]["_id"]], name="guess_"..no["evaluator"]["_rounds"].."_#"}
        no["ball"]["_col_used"] = true                               -- every color can be set only once
    end
end

function evaluate(value, sender)
    if #no["guess_"..sender["_rounds"].."_#*"] ~= 4 then
        return    -- only operate on a full guess
    end
    if sender["_active"] then
        -- check user guess
        anchorpos = no["chooser_p_%1"] + 2*no["evaluator"]["_rounds"]*W +W
        local correct_pos = 0
        local correct_col = 0
        for i=0, 3 do
            col_to_check = fl(anchorpos+i*S):kind()
            if col_to_check == solution[i+1] then
                -- color at correct position
                correct_pos = correct_pos +1
            else
                -- check if color appears in solution, this implies color at wrong position
                for j=1,4 do
                    if col_to_check == solution[j] then
                        correct_col = correct_col +1
                        break
                    end
                end
            end
        end
        -- give feedback
        local k = 0
        for i=1, correct_pos do
            wo[anchorpos + 5*S + k*S] = {"st_break_black"}
            k = k+1
        end
        for i=1, correct_col do
            wo[anchorpos + 5*S + k*S] = {"st_break_white"}
            k = k+1
        end
        if correct_pos == 4 then
            -- solution found, stop the game and open the door
            sender["_active"] = false
            no["thedoor"]:open()
        elseif sender["_rounds"] == 0 then
            -- no more tries left, game over and print solution
            sender["_active"] = false
            for i=1,4 do
                wo[sender + 5*E + (5-i)*N] = {solution[i]}
            end
            wo[no["thedoor"]] = {"st_death"}
        else
            -- some tries left, prepare for next round
            sender["_rounds"] = sender["_rounds"] -1
            no["chooser_c*"]["_col_choosen"] = false
            no["chooser_p*"]["_col"] = ""
            no["ball"]["_col_used"] = false
        end
    end
end

-- set up game
local perm = lib.math.permutation(6)
solution = {colors[perm[1]], colors[perm[2]], colors[perm[3]], colors[perm[4]]}
wo[no["chooser_"..no["ball"]["_col"]] + E] = {"st_lightglass", name="marker"}
 ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
      <el:string el:key="text1">
        <el:english el:translate="true">Each color appears once. Each correct color produces whites in the wrong place, blacks in the right one.</el:english>
        <el:translation el:lang="fr">Chaque couleur n'existe qu'une fois au plus; un blanc pour une couleur bonne; un noir pour une couleur bonne et au bon endroit.</el:translation>
      </el:string>
      <el:string el:key="text2">
        <el:english el:translate="true">This switch is to validate your guess.</el:english>
        <el:translation el:lang="fr">Ce bouton valide votre choix.</el:translation>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>
