=== dheck/Enigma/data/schemas/level.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' targetNamespace="http://enigma-game.org/schema/level/1" xmlns:el="http://enigma-game.org/schema/level/1" elementFormDefault="qualified" attributeFormDefault="qualified" version="0.2" xml:lang="en">
  <xs:annotation>
    <xs:documentation>
      XML schema definitions for Enigma levels
      Copyright Â© 2006 Ronald Lamprecht
      GPL2
    </xs:documentation>
  </xs:annotation>
  <xs:element name="level">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="protected" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              The protected section is reserved for data from the level author.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="info" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="identity" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="titel" type="xs:string" use="required"/>
                        <xs:attribute name="subtitel" type="xs:string" use="optional"/>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- identity -->
                    <xs:element name="version" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="score" type="xs:unsignedShort" use="required"/>
                        <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                        <xs:attribute name="revision" use="required">
                          <xs:simpleType>
                            <xs:union memberTypes="xs:unsignedShort el:revisionType"/>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="status" type="el:statusType" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- version -->
                    <xs:element name="author" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" default="anonymous" use="optional"/>
                        <xs:attribute name="email" type="xs:anyURI" use="optional"/>
                        <xs:attribute name="homepage" type="xs:anyURI" use="optional"/>
                      </xs:complexType>
                    </xs:element> <!-- author -->
                    <xs:element name="copyright" minOccurs="1" maxOccurs="1" type="xs:string"/>
                    <xs:element name="license" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="type" type="xs:string" use="required"/>
                            <xs:attribute name="open" type="xs:boolean" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element> <!-- license -->
                    <xs:element name="compatibility" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dependency" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="path" type="xs:string" use="required"/>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                              <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                              <xs:attribute name="preload" type="xs:boolean" use="required"/>
                              <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                            </xs:complexType>
                          </xs:element> <!-- dependency -->
                          <xs:element name="externaldata" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="path" type="xs:string" use="optional"/>
                              <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                            </xs:complexType>
                          </xs:element> <!-- externaldata -->
                          <xs:element name="editor" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required"/>
                              <xs:attribute name="version" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element> <!-- editor -->
                          <xs:element name="extensions" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element> <!-- extensions -->
                        </xs:sequence>
                        <xs:attribute name="enigma" type="xs:float" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- compatibility -->
                    <xs:element name="modes" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="easy" type="xs:boolean" use="required"/>
                        <xs:attribute name="single" type="xs:boolean" use="required"/>
                        <xs:attribute name="network" type="xs:boolean" use="required"/>
                        <xs:attribute name="control" type="el:controlType" use="optional" default="force"/>
                        <xs:attribute name="scoreunit" type="el:scoreunitType" use="optional" default="duration"/>
                        <xs:attribute name="scoretarget" type="xs:string" use="optional" default="time"/>
                      </xs:complexType>
                    </xs:element> <!-- modes -->
                    <xs:element name="comments" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="credits" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:token">
                                  <xs:attribute name="showinfo" type="xs:boolean" use="optional" default="false"/>
                                  <xs:attribute name="showstart" type="xs:boolean" use="optional" default="false"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- credits -->
                          <xs:element name="dedication" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:token">
                                  <xs:attribute name="showinfo" type="xs:boolean" use="optional" default="false"/>
                                  <xs:attribute name="showstart" type="xs:boolean" use="optional" default="false"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- dedication -->
                          <xs:element name="code" minOccurs="0" maxOccurs="1" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element> <!-- comments -->
                    <xs:element name="update" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- update -->
                    <xs:element name="upgrade" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                        <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- upgrade -->
                    <xs:element name="preview" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
                      </xs:complexType>
                    </xs:element> <!-- preview -->
                    <xs:element name="score" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="easy" type="el:scoreType" use="required"/>
                        <xs:attribute name="difficult" type="el:scoreType" use="required"/> 
                      </xs:complexType>
                    </xs:element> <!-- score -->
                    
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>

                  </xs:sequence>
                  <xs:attribute name="type" type="el:fileType" use="required"/>
                </xs:complexType>
              </xs:element> <!-- info -->
              
              <xs:element name="elements" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- elements -->
              
              <xs:element name="luamain" minOccurs="0" maxOccurs="1" type="xs:string"/>
              
              <xs:any namespace="##other" minOccurs="0" maxOccurs="1" processContents="skip">
                <xs:annotation>
                  <xs:documentation>
                    Any external level editor is free to include an element of its own
                    namespace for storage of any extensions. This element is ignored by
                    enigma. The editor is free to supply an additional schema for its 
                    element definitions.
                  </xs:documentation>
                </xs:annotation>
              </xs:any>
              
              <xs:element name="i18n" minOccurs="1" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="string" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="english" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="translate" type="xs:boolean" default="true"/>
                                  <xs:attribute name="comment" type="xs:string" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- english -->
                          <xs:element name="translation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="lang" type="xs:language" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- translation -->
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- string -->
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- i18n -->
              
              <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>

            </xs:sequence>
            <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
          </xs:complexType>
        </xs:element> <!-- protected -->
        
        <xs:element name="public" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              The pubic section for not validated additions by others. All info
              in public is handeled with care by enigma. Translations will be
              suggested to the official translators and only be used if confirmed
              or missing in the translators translations.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="i18n" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="string" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="translation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="lang" type="xs:language" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- translation -->
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:ID" use="required">
                          <xs:annotation>
                            <xs:documentation>
                              Usage of type xs:ID instead of xs:string is required by evaluation
                              XSLT stylesheets. 
                              It limits the public/i18n/strings to key-identifier usage instead
                              of original complete english string as key usage. But this is not
                              too bad, because it reduces errors due to changed english strings 
                              in the protected area.
                              The ID type guarantees us uniqueness within public/i18n and allows
                              stylesheets and programs to use XPaths to crossover from a 
                              protected/i18n/string to the corresponding public/i18n/string.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element> <!-- string -->
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- i18n -->
              <xs:element name="upgrade" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="url" type="xs:anyURI" use="required"/>
                  <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                </xs:complexType>
              </xs:element> <!-- upgrade -->
              <xs:element name="extensions" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- extensions -->
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- public -->
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="stringkey">
      <xs:selector xpath="el:protected/el:i18n/el:string"/>
      <xs:field xpath="@el:key"/>
    </xs:key>
    <xs:keyref name="translationkey" refer="el:stringkey">
      <xs:selector xpath="el:public/el:i18n/el:string"/>
      <xs:field xpath="@el:key"/>
    </xs:keyref>
  </xs:element>
  
  <xs:simpleType name="fileType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="level"/>
      <xs:enumeration value="multilevel"/>
      <xs:enumeration value="library"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="revisionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="$Revision[ ]*[\d]*[ ]*$"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="statusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="released"/>
      <xs:enumeration value="stable"/>
      <xs:enumeration value="test"/>
      <xs:enumeration value="experimental"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="controlType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="force"/>
      <xs:enumeration value="balance"/>
      <xs:enumeration value="key"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreunitType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="duration"/>
      <xs:enumeration value="number"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreType">
    <xs:restriction base="xs:string">
      <xs:pattern value="-|([ \d]?\d:[012345]\d)|(\d)+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== dheck/Enigma/data/levels/enigma_v/martin30_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="The Prison" el:subtitle="" el:id="martin30"/>
      <el:version el:score="1" el:release="1" el:revision="0" el:status="released"/>
      <el:author  el:name="Martin Hawlisch" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2003 Martin Hawlisch</el:copyright>
      <el:license el:type="GPL version 2" el:open="true"/>
      <el:compatibility el:enigma="0.92">
      </el:compatibility>
      <el:modes el:easy="false" el:single="true" el:network="false"/>
      <el:comments>
        <el:code>Lua 5.1 and XML converted by Leveladministrators</el:code>
      </el:comments>
      <el:score el:easy="-" el:difficult="-"/>
    </el:info>
    <el:luamain><![CDATA[
levelw = 20
levelh = 13

stone="st-thief"
create_world( levelw, levelh)
draw_border( stone)
fill_floor( "fl-brick", 0, 0, levelw, levelh)

draw_stones( stone, { 1,3}, {2,0}, 4)
draw_stones( stone, {12,3}, {2,0}, 4)
draw_stones( stone, { 1,9}, {2,0}, 4)
draw_stones( stone, {12,9}, {2,0}, 4)
draw_stones( stone, { 4,1}, {0,1}, 3)
draw_stones( stone, { 8,1}, {0,1}, 3)
draw_stones( stone, {11,1}, {0,1}, 3)
draw_stones( stone, {15,1}, {0,1}, 3)
draw_stones( stone, { 4,9}, {0,1}, 3)
draw_stones( stone, { 8,9}, {0,1}, 3)
draw_stones( stone, {11,9}, {0,1}, 3)
draw_stones( stone, {15,9}, {0,1}, 3)
draw_stones( stone, { 2,6}, {1,0},16)

doorh(2,3,{name="door1"})
set_stone("st-floppy", 4, 4, {action="openclose", target="door1"})
doorh(6,3,{name="door2"})
set_stone("st-floppy", 8, 4, {action="openclose", target="door2"})
doorh(2,9,{name="door3"})
set_stone("st-floppy", 4, 8, {action="openclose", target="door3"})
doorh(6,9,{name="door4"})
set_stone("st-floppy", 8, 8, {action="openclose", target="door4"})
doorh(13,3,{name="door5"})
set_stone("st-floppy", 11, 4, {action="openclose", target="door5"})
doorh(17,3,{name="door6"})
set_stone("st-floppy", 15, 4, {action="openclose", target="door6"})
doorh(13,9,{name="door7"})
set_stone("st-floppy", 11, 8, {action="openclose", target="door7"})
doorh(17,9,{name="door8"})
set_stone("st-floppy", 15, 8, {action="openclose", target="door8"})

set_item("it-floppy", 10, 11)
document( 9, 4, "text1")

oxyd( 2, 0)
oxyd( 6, 0)
oxyd(13, 0)
oxyd(17, 0)
oxyd( 2,12)
oxyd( 6,12)
oxyd(13,12)
oxyd(17,12)
oxyd_shuffle()

set_actor("ac-blackball", 10, 2.5)
    ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
      <el:string el:key="text1">
        <el:english el:translate="true">Warning ... ... thieves!</el:english>
      </el:string> 
    </el:i18n>
  </el:protected>
</el:level>

=== dheck/Enigma/data/levels/enigma_ix/pulley17_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Logic Gates" el:subtitle="" el:id="20080601pulley001"/>
      <el:version el:score="2" el:release="2" el:revision="2" el:status="released"/>
      <el:author  el:name="Mark Pulley" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2008 Mark Pulley</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="1.10"/>
      <el:modes el:easy="true" el:single="true" el:network="false"/>
      <el:score el:easy="5:38" el:difficult="4:35"/>
    </el:info>
    <el:luamain><![CDATA[
wo["FollowGrid"] = true
wo["FollowMethod"] = FOLLOW_SCROLL
wo["FollowThreshold"] = po(4, 3)

ti[" "] = {"fl_bright"}
ti[">"] = {"fl_slope_te"} -- Right
ti["<"] = {"fl_slope_tw"} -- Left
ti["^"] = {"fl_slope_tn"} -- Up
ti["v"] = {"fl_slope_ts"} -- Down
ti["e"] = {"st_oneway_black", state=EAST}
ti["s"] = {"st_oneway_black", state=SOUTH}
ti["w"] = {"st_oneway_black", state=WEST}
ti["E"] = ti[">"] .. {"st_oneway_black", state=EAST}
ti["N"] = ti["^"] .. {"st_oneway_black", state=NORTH}
ti["S"] = ti["v"] .. {"st_oneway_black", state=SOUTH}
ti["W"] = ti["<"] .. {"st_oneway_black", state=WEST}
ti["("] = ti["<"] .. {"st_oneway", state=WEST}
ti[")"] = ti[">"] .. {"st_oneway", state=WEST}
ti["-"] = ti["w"] .. {"it_sensor", "westsensor#", target="mark", _dir=W}
ti["="] = ti["e"] .. {"it_sensor", "eastsensor#", target="mark", _dir=E}
ti["0"] = {"st_oxyd"}
ti["#"] = {"st_bluegray"}

if wo ["IsDifficult"] then
  ti["d"] = ti["#"]
  ti["."] = ti[">"]
  ti["f"] = ti[">"]
else
  ti["d"] = {"st_dispenser_extralife"}
  ti["."] = ti[">"] .. {"it_spoon"}
  ti["f"] = ti[">"] .. {"it_flag_black"}
end

ti["*"] = cond(wo["CreatingPreview"], ti[" "] .. {"ac_marble_black", 0.5, 0.5}, ti[" "])
ti["@"] = cond(wo["CreatingPreview"], ti[">"], ti[">"] .. {"#ac_marble_black"})

--          1    1    2    2    3    3    4    4    5    5    6    6    7    7    8    8
--0    5    0    5    0    5    0    5    0    5    0    5    0    5    0    5    0    5
wo(ti, " ", {
 "#######################################d###########################################",
 "#@>>.>f>.>f>>>E                                                 W<<<<<<<<<<<<<<<<<#", --01
 "###############s#######s#######s#######s#######s#######s#######s#################N#",
 "#         #s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s#           #^#",
 "#     #####s#######s#######s#######s#######s#######s#######s#######s####        #^#",
 "#     #s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s#       #^#", --05
 "# #####s#######s#######s#######s#######s#######s#######s#######s#######s####    #^#",
 "# #s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s#   #^#",
 "# #s#######s#######s#######s#######s#######s#######s#######s#######s#######s#   #^#",
 "# # eees-w( )e=s-w( )e=s-w( )e=sww(*)ees-w( )e=s-w( )e=s-w( )e=s-w( )e=swww #   #^#",
 "# #####s#######s#######s#######s#######s#######s#######s#######s#######s#####   #^#", --10
 "# #s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s#   #^#",
 "# #s#######s#######s#######s#######s#######s#######s#######s#######s#######s#   #^#",
 "# # eees-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=swww #   #^#",
 "# #####s#######s#######s#######s#######s#######s#######s#######s#######s#####   #^#",
 "# #s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s#   #^#", --15
 "# #s#######s#######s#######s#######s#######s#######s#######s#######s#######s#   #^#",
 "# # eees-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=swww #   #^#",
 "# #####s#######s#######s#######s#######s#######s#######s#######s#######s#####   #^#",
 "# #s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s-w( )e=s#   #^#",
 "###s#######s#######s#######s#######s#######s#######s#######s#######s#######s#####^#", --20
 "#      0#      0#      0#      0#      0#      0#      0#      0#      0#      0#^#",
 "#s#######s#######s#######s#######s#######s#######s#######s#######s#######s#######^#",
 "#>>>>>>>E>>>>>>>E>>>>>>>E>>>>>>>E>>>>>>>E>>>>>>>E>>>>>>>E>>>>>>>E>>>>>>>E>>>>>>>E^#",
 "###################################################################################"}) --24
--          1    1    2    2    3    3    4    4    5    5    6    6    7    7    8    8
--0    5    0    5    0    5    0    5    0    5    0    5    0    5    0    5    0    5

wo:add({"ot_timer", target="rotate", state=ON, interval=0.1, loop=true})
wo:shuffleOxyd()

function flip(value, sender)
   st(sender - 2*sender["_dir"]):flip()
   st(sender - 4*sender["_dir"]):flip()
end

for sensor in no["westsensor#*"]:shuffle():sub(1, 37) do
   flip(true, sensor)
end

active_sensors = {}

function mark(value, sender)
   sender["_count"] = 6
   sender["_rot"] = cond(math.random() > 0.5, 1, -1)
   table.insert(active_sensors, sender)
end

function rotate(value, sender)
   for i=#active_sensors, 1, -1 do
       local sensor = active_sensors[i]
       local dir = st(sensor - 2*sensor["_dir"])["state"]
       dir = (dir + sensor["_rot"]) % 4
       st(sensor - 2*sensor["_dir"])["state"] = dir
       st(sensor - 4*sensor["_dir"])["state"] = dir
       sensor["_count"] = sensor["_count"] - 1
       if sensor["_count"] == 0 then
           table.remove(active_sensors, i)
       end
   end
end
 ]]></el:luamain>
   <el:i18n>
     <el:string el:key="title">
       <el:english el:translate="false"/>
     </el:string>
   </el:i18n>
 </el:protected>
</el:level>

=== dheck/Enigma/data/levels/enigma_ix/devnull54_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Two Is A Company V" el:subtitle="" el:id="devnull54"/>
      <el:version el:score="1" el:release="1" el:revision="1" el:status="released"/>
      <el:author el:name="/dev/null" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2009, 2010 dev0</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="1.10"/>
      <el:modes el:easy="false" el:single="true" el:network="true"/>
      <el:score el:easy="-" el:difficult="5:00"/>
    </el:info>
    <el:luamain><![CDATA[
wo["AutoRespawn"] = true
wo["AllowSuicide"] = false

ti["#"] = {"st_redrock"}
ti[" "] = {"fl_concrete"}
ti["~"] = {"fl_water"}
ti["B"] = {"st_door_a", name = "doorWhite"}
ti["W"] = {"st_door_a", name = "doorBlack"}
ti["b"] = ti["~"] .. {"it_shogun_l", target = "doorWhite"}
ti["w"] = ti["~"] .. {"it_shogun_l", target = "doorBlack"}
ti["u"] = {"st_blocker", name = "blockerBlack#"}
ti["U"] = {"st_blocker", name = "blockerWhite#"}
ti["t"] = {"fl_scales_concrete", target = "scalesBlack", action = "signal"}
ti["T"] = {"fl_scales_concrete", target = "scalesWhite", action = "signal"}
ti["S"] = {"st_shogun", flavor = "sml"}
ti["o"] = {"st_oxyd_a", name = "north#"}
ti["O"] = {"st_oxyd_a", name = "south#"}
ti["@"] = {"#ac_marble_black"}
ti["A"] = {"#ac_marble_white"}

wo(ti, " ", {
    "##################o#",
    "# ~       A       Wo",
    "# T  ~ ~ ~ ~~  ~S  #",
    "#~~~T  ~ ~ ~~ ~ ~  #",
    "#~ ~~~T    ~~t~    #",
    "#~u~ ~~~~  w~U~t~  #",
    "#~T~u~ ~~##~~ ~U~t~#",
    "#~ ~T~u~b  ~~~~ ~U~#",
    "#    ~T~~~   t ~~ ~#",
    "# ~ ~~ ~~ ~  ~ t ~~#",
    "#  S ~ ~~  ~   ~ t #",
    "OB       @         #",
    "#O##################"})

wo:shuffleOxyd({"north#*", max = 0}, {"south#*", max = 0})
wo:add({"ot_counter", "scalesBlack", state = 0, target = "blockerBlack#*", action_3 = "open", action_2 = "close"})
wo:add({"ot_counter", "scalesWhite", state = 0, target = "blockerWhite#*", action_3 = "open", action_2 = "close"})
 ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>
